### ISSUE TITLE
Upstreaming as an octodns module

### ISSUE THREAD

**Issue by onny** [Janik-Haag/NixOS-DNS#9]
Would it be possible to upstream some of your work as a octodns module? Something like

```
services.octodns = {
  enable = true;
  providers = [ ... ];
  zoneConfig = { ... };
};
```

Not sure if upstream nixpkgs maintainers would accept this since this is not a classical service.

Best regards
Jonas

**Comment by Janik-Haag** [comment]
I don't see which part I could upstream/what would be sensible. nixpkgs is very focused on single host modules and the only module imported by the host is the one allowing you to specify the domain information. You could do something like having a systemd unit that periodically executes octodns and syncs everything but that introduces state management and bootstrapping problems for dns-tls challenge verification. I just deploy octodns as a ci job that runs if someone commits to main.
